tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ansible"
brew "glib"
brew "certbot"
brew "dep"
brew "dog"
brew "emojify"
brew "unbound"
brew "gnupg"
brew "gobject-introspection"
brew "graphviz"
brew "htop"
brew "imagemagick"
brew "iperf3"
brew "ipfs", restart_service: true
brew "jq"
brew "lean-cli"
brew "less"
brew "mas"
brew "mtr"
brew "mysql"
brew "neofetch"
brew "nmap"
brew "node"
brew "node@12"
brew "pass"
brew "pinentry-mac"
brew "smartmontools"
brew "socat"
brew "ssh-copy-id"
brew "sysbench"
brew "telnet"
brew "websocat"
brew "wget"
brew "wrk"
cask "aerial"
cask "bitbar"
cask "brave-browser"
cask "caffeine"
cask "clashx"
cask "docker"
cask "downie"
cask "firefox"
cask "font-fira-code"
cask "gitup"
cask "google-chrome"
cask "handbrake"
cask "iina"
cask "intel-power-gadget"
cask "netnewswire"
cask "obs"
cask "paw"
cask "pock"
cask "scroll-reverser"
cask "softu2f"
cask "squirrel"
cask "steam"
cask "telegram"
cask "visual-studio-code"
cask "zulip"
mas "Affinity Photo", id: 824183456
mas "Bitwarden", id: 1352778147
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Medis", id: 1063631769
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "QQ", id: 451108668
mas "Reeder", id: 1449412482
mas "Ulysses", id: 1225570693
mas "WeChat", id: 836500024
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
